name: x_kit
description: Stop doing troublesome things.
version: 0.0.2
homepage:

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  #https://pub.dev/packages/flutter_riverpod
  flutter_riverpod: ^2.3.6

  simple_logger: ^1.9.0
  talker_flutter: ^3.1.5

  # https://pub.dev/packages/cached_network_image
  cached_network_image: ^3.2.2

  #https://pub.dev/packages/modal_bottom_sheet
  # modal_bottom_sheet: ^2.1.2

  # https://pub.dev/packages/expandable
  expandable: ^5.0.1

  #https://pub.dev/packages/flutter_scale_tap
  flutter_scale_tap: ^1.0.5

  # https://pub.dev/packages/loading_overlay
  loading_overlay: ^0.3.0

  #https://pub.dev/packages/loading_animation_widget
  loading_animation_widget: ^1.2.0+3

  #https://pub.dev/packages/fluentui_icons
  fluentui_icons: ^1.0.0
  fluentui_system_icons: ^1.1.168
  flutter_phosphor_icons: ^0.0.1+6
  flutter_iconly: ^1.0.2

  flutter_font_icons: ^2.2.4

  #https://pub.dev/packages/adaptive_dialog/install
  adaptive_dialog: ^1.8.2

  #https://pub.dev/packages/currency_formatter
  currency_formatter: ^2.0.0

  nested: ^1.0.0

  go_router: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
