name: x_kit
description: Stop doing troublesome things.
version: 0.0.2
homepage:

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  #https://pub.dev/packages/flutter_riverpod
  flutter_riverpod: ^2.4.5

  # https://pub.dev/packages/firebase_core
  firebase_core: ^2.22.0
  # https://pub.dev/packages/cloud_firestore
  cloud_firestore: ^4.13.0

  json_annotation: ^4.8.1

  simple_logger: ^1.9.0+3
  talker_flutter: ^3.1.5

  # https://pub.dev/packages/cached_network_image
  cached_network_image: ^3.3.0

  #https://pub.dev/packages/modal_bottom_sheet
  modal_bottom_sheet: ^3.0.0-pre

  # https://pub.dev/packages/expandable
  expandable: ^5.0.1

  #https://pub.dev/packages/flutter_scale_tap
  flutter_scale_tap: ^1.0.5

  # https://pub.dev/packages/loading_overlay
  loading_overlay: ^0.3.0

  #https://pub.dev/packages/loading_animation_widget
  loading_animation_widget: ^1.2.0+3

  #https://pub.dev/packages/fluentui_icons
  fluentui_icons: ^1.0.0
  fluentui_system_icons: ^1.1.168
  flutter_phosphor_icons: ^0.0.1+6
  flutter_iconly: ^1.0.2

  flutter_font_icons: ^2.2.4

  #https://pub.dev/packages/adaptive_dialog/install
  adaptive_dialog: ^1.10.0

  #https://pub.dev/packages/currency_formatter
  currency_formatter: ^2.1.0

  nested: ^1.0.0

  go_router: ^12.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1